version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
    - mysql
    healthcheck:
      test: "mysqladmin ping -h localhost"
      interval: 1s
      timeout: 1s
      retries: 60


  app:
    depends_on:
      - mysql
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    stdin_open: true
    tty: true
    command: bash -c "pnpm prisma:push && pnpm populate && pnpm build && pnpm start"
    networks:
      - mysql


volumes: 
  db:

networks:
  mysql:
    driver: bridge